sudo: required
language: minimal
python: 2.7

services:
  - docker

env:
  - TOX_ENV=py27

git:
  submodules: false

before_install:
  - wget https://raw.githubusercontent.com/bgruening/galaxy-flavor-testing/master/Makefile
  - make docker_install
  - travis_wait 45 make docker_build
  - make docker_run
  - travis_wait 15 sleep 600

install:
  - make install

script:
  - make test_api
  - make test_ftp
  - df -h
  - #make test_bioblend
  - make test_docker_in_docker
