sudo: required
language: minimal
python: 2.7

services:
  - docker

env:
  - TOX_ENV=py27

before_install:
  - wget https://raw.githubusercontent.com/bgruening/galaxy-flavor-testing/master/Makefile
  - make docker_install
  - sudo apt-get -qq update
  - sudo apt-get install -y python-dev
  - travis_wait 45 make docker_build
  - make docker_run
  - sleep 60

install:
  - make install

script:
  - make test_api
  - make test_ftp
  - make test_bioblend
  - make test_docker_in_docker
